### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by jerkyrs** [iotexproject/iotex-core#12]
What I did
Build and run container 
```
make docker
docker run -t -i IMAGENAME /bin/bash
```
Inside docker container i attempt to run iotex-server

```
root@4fa675318289:/go# iotex-server -log-path=/var/log/iotex/server.log -config=/etc/iotex/config.yaml
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/iotexproject/iotex-core/common/utils.GetFileAbsPath(0xa2567d, 0x14, 0xc42002c500, 0xc42009c198)
        /go/src/github.com/iotexproject/iotex-core/common/utils/fileutils.go:32 +0x296
github.com/iotexproject/iotex-core/blockchain.NewGenesisBlock(0xc4201a8900, 0x0)
        /go/src/github.com/iotexproject/iotex-core/blockchain/genesis.go:82 +0xe55
github.com/iotexproject/iotex-core/blockchain.createAndInitBlockchain(0xa94660, 0xc4201894c0, 0xa94420, 0xc4200c0300, 0xc4201a8900, 0x9bfc20, 0xc4200c0300)
        /go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:512 +0x1cb
github.com/iotexproject/iotex-core/blockchain.CreateBlockchain(0xc4201a8900, 0xa94420, 0xc4200c0300, 0xa94420, 0xc4200c0300)
        /go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:405 +0x97
github.com/iotexproject/iotex-core/server/itx.NewServer(0xc4200949e0, 0x9, 0xc420094a10, 0xf, 0x77359400, 0x2540be400, 0x3b9aca00, 0x12a05f200, 0x3b9aca00, 0x0, ...)
        /go/src/github.com/iotexproject/iotex-core/server/itx/itxserver.go:45 +0x158
main.main()
        /go/src/github.com/iotexproject/iotex-core/server/main.go:50 +0x84
```

After running it manually the second time i get the following error
```
root@4fa675318289:/go# iotex-server -log-path=/var/log/iotex/server.log -config=/etc/iotex/config.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x86d67c]

goroutine 1 [running]:
github.com/iotexproject/iotex-core/blockchain.createAndInitBlockchain(0xa94660, 0xc42018b4c0, 0xa94420, 0xc4200c2300, 0xc4201aa900, 0x9bfc20, 0xc4200c2300)
        /go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:495 +0x12c
github.com/iotexproject/iotex-core/blockchain.CreateBlockchain(0xc4201aa900, 0xa94420, 0xc4200c2300, 0xa94420, 0xc4200c2300)
        /go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:405 +0x97
github.com/iotexproject/iotex-core/server/itx.NewServer(0xc4200949e0, 0x9, 0xc420094a10, 0xf, 0x77359400, 0x2540be400, 0x3b9aca00, 0x12a05f200, 0x3b9aca00, 0x0, ...)
        /go/src/github.com/iotexproject/iotex-core/server/itx/itxserver.go:45 +0x158
main.main()
        /go/src/github.com/iotexproject/iotex-core/server/main.go:50 +0x84
```

**Comment by Zhen-iotex** [comment]
Since the server is run as docker container, inside the docker container, the config yaml file should contain a genesisActionsPath variable inside chain setting, this path should contain the testnet_actions.yaml file.

**Comment by jerkyrs** [comment]
Certainly now starts but i get following

```
{"level":"warn","time":"2018-07-04T09:59:56Z","message":"discard leaf"}
{"level":"warn","time":"2018-07-04T09:59:58Z","message":"discard leaf"}
{"level":"warn","time":"2018-07-04T09:59:59Z","message":"discard leaf"}
{"level":"info","time":"2018-07-04T10:00:03Z","message":"Starting dispatcher"}
{"level":"info","scheme":"NOOP","time":"2018-07-04T10:00:03Z","message":"Starting IotxConsensus scheme"}
{"level":"error","error":"listen tcp: address 127.0.0.1::42124: too many colons in address","time":"2018-07-04T10:00:03Z","message":"Chain server failed to listen"}
{"level":"info","addr":"127.0.0.1:10000","time":"2018-07-04T10:00:03Z","message":"start PRC server"}
```

Probably this is config.yaml

```
config.yaml:    addr: "127.0.0.1::42124"
```

**Comment by jerkyrs** [comment]
I tested locally modifying the config.yaml as suspected (i realize this is unrelated to original ticket)

```
{"level":"warn","time":"2018-07-04T10:07:37Z","message":"discard leaf"}
{"level":"warn","time":"2018-07-04T10:07:38Z","message":"discard leaf"}
{"level":"warn","time":"2018-07-04T10:07:39Z","message":"discard leaf"}
{"level":"info","time":"2018-07-04T10:07:44Z","message":"Starting dispatcher"}
{"level":"info","scheme":"NOOP","time":"2018-07-04T10:07:44Z","message":"Starting IotxConsensus scheme"}
{"level":"info","addr":"127.0.0.1:42124","time":"2018-07-04T10:07:44Z","message":"Chain server is listening"}
{"level":"info","addr":"127.0.0.1:10000","time":"2018-07-04T10:07:44Z","message":"start PRC server"}
```

**Comment by zjshen14** [comment]
cc @Zhen-iotex

**Comment by Zhen-iotex** [comment]
Thanks for pointing it out, the extra colon is removed
