### ISSUE TITLE
Flaky rolldpos test

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1288]
**Which jobs are failing**:
On laptop
**Which test(s) are failing**:
Only know inside rolldpos package
**Since when has it been failing**:
For quite a long time
**Testgrid link**:
N/A
**Reason for failure**:
N/A
**Anything else we need to know**:
Log: https://gist.github.com/zjshen14/e0224767d3bd5a38f2884e62b91680ea

**Comment by zjshen14** [comment]
Encounter another related failure

```
2019-06-21T12:14:50.551-0700	ERROR	rolldpos/rolldposctx.go:475	invalid message type	{"height": 33, "epoch": 3, "round": 1, "proposer": "io1juvx5g063eu4ts832nukp4vgcwk2gnc5cu9ayd", "numProposals:": 0, "numLocks:": 0, "numCommits:": 0, "message": null}
github.com/iotexproject/iotex-core/consensus/scheme/rolldpos.(*rollDPoSCtx).Broadcast
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/scheme/rolldpos/rolldposctx.go:475
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).onBroadcastPreCommitEndorsement
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:523
github.com/iotexproject/go-fsm.(*fsm).Handle
	/Users/zjshen/Projects/go/pkg/mod/github.com/iotexproject/go-fsm@v1.0.0/fsm.go:178
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).handle
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:332
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).Start.func1
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:231
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e57c98]

goroutine 5157 [running]:
github.com/iotexproject/iotex-core/consensus/scheme/rolldpos.(*EndorsedConsensusMessage).Proto(0x0, 0x536809a, 0x14, 0xc000783640)
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/scheme/rolldpos/endorsedconsensusmessage.go:53 +0x48
github.com/iotexproject/iotex-core/consensus/scheme/rolldpos.(*rollDPoSCtx).Broadcast(0xc000601ad0, 0x522f020, 0x0)
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/scheme/rolldpos/rolldposctx.go:477 +0xc1
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).onBroadcastPreCommitEndorsement(0xc00026e240, 0x56ccac0, 0xc001d5a120, 0x403f1bb, 0xc00008ed80, 0xc0013e57c8, 0x40629c2)
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:523 +0x120
github.com/iotexproject/go-fsm.(*fsm).Handle(0xc000a8e9f0, 0x56ccac0, 0xc001d5a120, 0x0, 0x0)
	/Users/zjshen/Projects/go/pkg/mod/github.com/iotexproject/go-fsm@v1.0.0/fsm.go:178 +0x202
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).handle(0xc00026e240, 0xc001d5a120, 0x2, 0x1)
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:332 +0x802
github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).Start.func1(0xc00026e240)
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:231 +0x185
created by github.com/iotexproject/iotex-core/consensus/consensusfsm.(*ConsensusFSM).Start
	/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/consensus/consensusfsm/fsm.go:224 +0x6a
FAIL	github.com/iotexproject/iotex-core/e2etest	79.890s
```
