### ISSUE TITLE
Making full node be able to run on arm arch hardware

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-core#1352]

**Comment by simonerom** [comment]
After building iotex-core, here is the output if I go into db directory and run tests. @dustinxie 

```
pi@raspberrypi:~/iotex-core $ cd db
pi@raspberrypi:~/iotex-core/db $ go test
badger 2019/07/10 17:47:58 INFO: All 0 tables opened in 0s
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa5 pc=0x6adfec]

goroutine 10 [running]:
testing.tRunner.func1(0x22de460)
    /usr/local/go/src/testing/testing.go:830 +0x364
panic(0x7c1408, 0x10409a8)
    /usr/local/go/src/runtime/panic.go:522 +0x1a0
github.com/dgraph-io/badger.(*DB).Update(0x0, 0x204dee0, 0x0, 0x0)
    /home/pi/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190226225317-8115aed38f8f/txn.go:742 +0x24
github.com/iotexproject/iotex-core/db.(*badgerDB).Put(0x219a4b0, 0x868364, 0x8, 0x202617c, 0x3, 0x3, 0x2026180, 0x5, 0x5, 0xb6dc0004, ...)
    /home/pi/iotex-core/db/db_badger.go:51 +0xac
github.com/iotexproject/iotex-core/db.TestKVStorePutGet.func1(0xaccbf8, 0x219a4b0, 0x22de460)
    /home/pi/iotex-core/db/db_test.go:44 +0x190
github.com/iotexproject/iotex-core/db.TestKVStorePutGet.func4(0x22de460)
    /home/pi/iotex-core/db/db_test.go:75 +0xa8
testing.tRunner(0x22de460, 0x2010408)
    /usr/local/go/src/testing/testing.go:865 +0xa4
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:916 +0x2b8
exit status 2
FAIL    github.com/iotexproject/iotex-core/db    0.451s
pi@raspberrypi:~/iotex-core/db $ 
```

**Comment by simonerom** [comment]
After some tests on different versions of Raspberries and different OS, I found the problem is with boltDB either with the OS or the Golang armv6l architecture.

The official Raspbian Linux image uses armv6l architecture so it's not suitable. The Ubuntu images work well, but they are still not available for the new Raspberry Pi 4. Kali Linux is the only other image currently available for the RPI 4, but it's armv6l too.

So eventually, I could make it work going back to the Raspberry PI 3 with 1GB, but for which there are Ubuntu  OS images available with arm64 architecture.

**Comment by raullenchai** [comment]
https://www.youtube.com/watch?v=xWD4UhGGCyo

Thanks @simonerom
