### ISSUE TITLE
panic on db init

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core#1657]
```
unexpected fault address 0x7f1e95a88008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1e95a88008 pc=0xce4814]

goroutine 1 [running]:
runtime.throw(0x12cf0bf, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0005eac88 sp=0xc0005eac58 pc=0x43d442
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0005eacb8 sp=0xc0005eac88 pc=0x452e01
go.etcd.io/bbolt.(*Cursor).search(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x95a88)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:249 +0x64 fp=0xc0005ead58 sp=0xc0005eacb8 pc=0xce4814
go.etcd.io/bbolt.(*Cursor).searchPage(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x7f1e00094000)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:308 +0x153 fp=0xc0005eade8 sp=0xc0005ead58 pc=0xce4da3
go.etcd.io/bbolt.(*Cursor).search(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x94)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:265 +0x18b fp=0xc0005eae88 sp=0xc0005eade8 pc=0xce493b
go.etcd.io/bbolt.(*Cursor).searchPage(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x7f1e0009b000)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:308 +0x153 fp=0xc0005eaf18 sp=0xc0005eae88 pc=0xce4da3
go.etcd.io/bbolt.(*Cursor).search(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x9b)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:265 +0x18b fp=0xc0005eafb8 sp=0xc0005eaf18 pc=0xce493b
go.etcd.io/bbolt.(*Cursor).seek(0xc0005eb098, 0x219b368, 0xb, 0xb, 0x7f1e0009c02a, 0x10, 0x10, 0x1, 0x100298178, 0x10, ...)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/cursor.go:159 +0x7e fp=0xc0005eb028 sp=0xc0005eafb8 pc=0xce410e
go.etcd.io/bbolt.(*Bucket).Get(0xc0002e4500, 0x219b368, 0xb, 0xb, 0xc0002e4500, 0x20, 0xc000298178)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/bucket.go:260 +0xbc fp=0xc0005eb0c8 sp=0xc0005eb028 pc=0xce105c
github.com/iotexproject/iotex-election/db.(*boltDB).Get.func1(0xc000138000, 0x1478668, 0xc000138000)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/db/kvstore.go:216 +0xd3 fp=0xc0005eb170 sp=0xc0005eb0c8 pc=0xcf7843
go.etcd.io/bbolt.(*DB).View(0xc000242000, 0xc0005eb230, 0x0, 0x0)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.2/db.go:719 +0x90 fp=0xc0005eb1c0 sp=0xc0005eb170 pc=0xce77f0
github.com/iotexproject/iotex-election/db.(*boltDB).Get(0xc00013a800, 0x12d4fa1, 0xa, 0x219b368, 0xb, 0xb, 0x43c1bf, 0xc0001eb230, 0xc0005eb2f0, 0x28, ...)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/db/kvstore.go:211 +0xe2 fp=0xc0005eb278 sp=0xc0005eb1c0 pc=0xcf74d2
github.com/iotexproject/iotex-election/db.(*KVStoreWithNamespaceWrapper).Get(0xc0005ee280, 0x219b368, 0xb, 0xb, 0x160dfa0, 0xc0001e7500, 0xc0005eb448, 0x0, 0x3)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/db/kvstore.go:119 +0x6a fp=0xc0005eb2e0 sp=0xc0005eb278 pc=0xcf708a
github.com/iotexproject/iotex-election/committee.(*archive).migrate(0xc00026d810, 0x160dfa0, 0xc0001e7500, 0x0, 0x0)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/committee/pollarchive.go:308 +0x1a6 fp=0xc0005eb430 sp=0xc0005eb2e0 pc=0xd00286
github.com/iotexproject/iotex-election/committee.(*archive).Start(0xc00026d810, 0x160dfa0, 0xc0001e7500, 0x0, 0x0)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/committee/pollarchive.go:272 +0x2d2 fp=0xc0005eb4a8 sp=0xc0005eb430 pc=0xcffcb2
github.com/iotexproject/iotex-election/committee.(*committee).Start(0xc0002823f0, 0x160dfa0, 0xc0001e7500, 0x0, 0x0)
	/go/pkg/mod/github.com/iotexproject/iotex-election@v0.2.8/committee/committee.go:196 +0x96 fp=0xc0005eb500 sp=0xc0005eb4a8 pc=0xcf8b06
github.com/iotexproject/iotex-core/chainservice.(*ChainService).Start(0xc00026db20, 0x160dfa0, 0xc0001e7500, 0x0, 0x0)
	/go/apps/iotex-core/chainservice/chainservice.go:219 +0x2c9 fp=0xc0005eb540 sp=0xc0005eb500 pc=0xf0ea59
github.com/iotexproject/iotex-core/server/itx.(*Server).Start(0xc0001ce000, 0x160dfa0, 0xc0004f2000, 0xc00044e6e0, 0x12)
	/go/apps/iotex-core/server/itx/server.go:123 +0x13e fp=0xc0005eb5f0 sp=0xc0005eb540 pc=0xf12f0e
github.com/iotexproject/iotex-core/server/itx.StartServer(0x160dfa0, 0xc0004f2000, 0xc0001ce000, 0xc000138380, 0xc000449ec0, 0xc0004758a8, 0x7, 0x1251, 0xc000475878, 0x7, ...)
	/go/apps/iotex-core/server/itx/server.go:209 +0x5d fp=0xc0005ebb90 sp=0xc0005eb5f0 pc=0xf13c7d
main.main()
	/go/apps/iotex-core/server/main.go:101 +0x886 fp=0xc0005edf98 sp=0xc0005ebb90 pc=0xf17046
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0005edfe0 sp=0xc0005edf98 pc=0x43edac
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0005edfe8 sp=0xc0005edfe0 pc=0x46ccf1
```

**Comment by raullenchai** [comment]
Pls provide more info about how to repo @yutongp
