### ISSUE TITLE
Invalid page type: 0: 4

### ISSUE THREAD

**Issue by cdgriffith** [iotexproject/iotex-core#35]
go version go1.10.3 linux/amd64
Ubuntu 16.04.5 LTS  (Windows subsystem) 
commit b6bad29364cdccdbd26ca3b081598c9132c7f276   (had same issue with v2.0 zip) 

```bash
# $ make run
go build -o ./bin/server -v ./server
export LD_LIBRARY_PATH=/home/james/go/src/github.com/iotexproject/iotex-core/crypto/lib/::/home/james/go/src/github.com/iotexproject/iotex-core/crypto/lib
./bin/server -config-path=e2etest/config_local_delegate.yaml -log-colorful=true
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc420257738, 0xc4201fba30, 0x7, 0x8, 0x4)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/cursor.go:256 +0x388
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc420257738, 0xc4201fba30, 0x7, 0x8, 0x0, 0x0, 0xc420257710, 0x4cbce9, 0xab79e0, 0xc420232860, ...)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/cursor.go:159 +0xa5
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc420136638, 0xc4201fba30, 0x7, 0x8, 0xc4201fba37, 0x1, 0x0)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/bucket.go:172 +0xfa
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc420136638, 0xc4201fba30, 0x7, 0x8, 0x7, 0x8, 0xc4201fba30)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/bucket.go:206 +0x4d
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc420136620, 0xc4201fba30, 0x7, 0x8, 0x7, 0x8, 0x429ee9)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/tx.go:115 +0x4f
github.com/iotexproject/iotex-core/db.(*boltDB).PutIfNotExists.func1(0xc420136620, 0xa6d608, 0xc420136620)
        /home/james/go/src/github.com/iotexproject/iotex-core/db/db.go:137 +0x71
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4200ba1e0, 0xc420257920, 0x0, 0x0)
        /home/james/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/db.go:598 +0x90
github.com/iotexproject/iotex-core/db.(*boltDB).PutIfNotExists(0xc420232100, 0xa3ddec, 0x7, 0xc420230dc0, 0x20, 0x20, 0xc4201963c0, 0x140, 0x140, 0xd3506d5d43f640bb, ...)
        /home/james/go/src/github.com/iotexproject/iotex-core/db/db.go:136 +0xd0
github.com/iotexproject/iotex-core/trie.(*trie).putPatriciaNew(0xc420136380, 0xabb960, 0xc420234a40, 0x274a6c8ca32285bf, 0x115a25d95389566d)
        /home/james/go/src/github.com/iotexproject/iotex-core/trie/trie.go:572 +0x3ec
github.com/iotexproject/iotex-core/trie.(*trie).upsert(0xc420136380, 0xc420230ce5, 0x14, 0x1b, 0xc420139b00, 0xf3, 0xff, 0x0, 0xc4202373b0)
        /home/james/go/src/github.com/iotexproject/iotex-core/trie/trie.go:266 +0x2bb
github.com/iotexproject/iotex-core/trie.(*trie).Upsert(0xc420136380, 0xc420230ce5, 0x14, 0x1b, 0xc420139b00, 0xf3, 0xff, 0x0, 0x0)
        /home/james/go/src/github.com/iotexproject/iotex-core/trie/trie.go:119 +0xb2
github.com/iotexproject/iotex-core/state.(*factory).CreateState(0xc4200e6e70, 0xa588b4, 0x31, 0x2540be400, 0x1, 0x0, 0x996a40)
        /home/james/go/src/github.com/iotexproject/iotex-core/state/factory.go:172 +0x1b1
github.com/iotexproject/iotex-core/blockchain.(*blockchain).initStateFactory(0xc4200ab540, 0x0, 0x0)
        /home/james/go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:244 +0x77
github.com/iotexproject/iotex-core/blockchain.NewBlockchain(0xc4200af900, 0xc420257ed0, 0x2, 0x2, 0x0, 0x1f4)
        /home/james/go/src/github.com/iotexproject/iotex-core/blockchain/blockchain.go:199 +0x25e
github.com/iotexproject/iotex-core/server/itx.NewServer(0xc4200af900, 0x8)
        /home/james/go/src/github.com/iotexproject/iotex-core/server/itx/itxserver.go:39 +0x79
main.main()
        /home/james/go/src/github.com/iotexproject/iotex-core/server/main.go:47 +0x87
Makefile:129: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by zjshen14** [comment]
@cdgriffith it seems that you have a bad bolt db file on $PWD. Please try to delete `./chain.db` and `./bolt.db` and `make run` again

**Comment by cdgriffith** [comment]
I do not seem to have those files. 

```bash
# $ ls -a 

.         bin         .codecov.yml     crypto      explorer    iotxaddress  network    simulator  trie
..        blockchain  CODEOWNERS       db          .gitignore  LICENSE.md   pkg        state      txvm
accounts  blocksync   config           dispatch    Gopkg.lock  logger       proto      test       vendor
actpool   .circleci   consensus        Dockerfile  Gopkg.toml  Makefile     README.md  testutil
beacon    cli         CONTRIBUTING.md  e2etest     go.test.sh  misc         server     tools
```

```bash
# $ make clean; make fmt; make build
Cleaning...
go fmt ./...
go build -o ./bin/server -v ./server
go build -o ./bin/actioninjector -v ./tools/actioninjector
go build -o ./bin/addrgen -v ./tools/addrgen
go build -o ./bin/iotc -v ./cli/iotc
```

```bash
go build -o ./bin/server -v ./server
export LD_LIBRARY_PATH=:/home/james/go/src/github.com/iotexproject/iotex-core/crypto/lib:/home/james/go/src/github.com/iotexproject/iotex-core/crypto/lib
./bin/server -config-path=e2etest/config_local_delegate.yaml -log-colorful=true
panic: invalid page type: 0: 4

...
```

**Comment by zjshen14** [comment]
@vincentiotex can you help to see if you could reproduce the issue in the aforementioned environment?

**Comment by raullenchai** [comment]
Code changed a lot in the previous months. @cdgriffith is this still an issue for you?

**Comment by cdgriffith** [comment]
I actually no longer have that environment, but I tried it on a fresh 18.04 I had and it seems to work fine now. Thanks for the heads up!
